"""fix models

Revision ID: 7b8f17ba71b3
Revises: f7afcb8f4842
Create Date: 2026-02-21 02:27:12.321423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7b8f17ba71b3"
down_revision: Union[str, Sequence[str], None] = "f7afcb8f4842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_likes_id"), "likes", ["id"], unique=False)
    op.create_index(op.f("ix_likes_tweet_id"), "likes", ["tweet_id"], unique=False)
    op.create_index(op.f("ix_likes_user_id"), "likes", ["user_id"], unique=False)
    op.alter_column("medias", "tweet_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("tweets", sa.Column("author_id", sa.Integer(), nullable=False))
    op.add_column("tweets", sa.Column("content", sa.String(length=250), nullable=False))
    op.drop_index(op.f("ix_tweets_user_id"), table_name="tweets")
    op.create_index(op.f("ix_tweets_author_id"), "tweets", ["author_id"], unique=False)
    op.drop_constraint(op.f("tweets_user_id_fkey"), "tweets", type_="foreignkey")
    op.create_foreign_key(None, "tweets", "users", ["author_id"], ["id"])
    op.drop_column("tweets", "text")
    op.drop_column("tweets", "user_id")
    op.add_column("users", sa.Column("api_key", sa.String(length=100), nullable=False))
    op.create_index(op.f("ix_users_api_key"), "users", ["api_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_api_key"), table_name="users")
    op.drop_column("users", "api_key")
    op.add_column(
        "tweets",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tweets",
        sa.Column("text", sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "tweets", type_="foreignkey")
    op.create_foreign_key(
        op.f("tweets_user_id_fkey"), "tweets", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_tweets_author_id"), table_name="tweets")
    op.create_index(op.f("ix_tweets_user_id"), "tweets", ["user_id"], unique=False)
    op.drop_column("tweets", "content")
    op.drop_column("tweets", "author_id")
    op.alter_column("medias", "tweet_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("ix_likes_user_id"), table_name="likes")
    op.drop_index(op.f("ix_likes_tweet_id"), table_name="likes")
    op.drop_index(op.f("ix_likes_id"), table_name="likes")
    op.drop_table("likes")
    # ### end Alembic commands ###
