"""feat: add followers model

Revision ID: b4a55cc3dbae
Revises: f6010f032636
Create Date: 2026-02-19 16:04:51.751393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b4a55cc3dbae"
down_revision: Union[str, Sequence[str], None] = "f6010f032636"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("following_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["following_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_followers_follower_id"), "followers", ["follower_id"], unique=False
    )
    op.create_index(
        op.f("ix_followers_following_id"), "followers", ["following_id"], unique=False
    )
    op.create_index(op.f("ix_followers_id"), "followers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_followers_id"), table_name="followers")
    op.drop_index(op.f("ix_followers_following_id"), table_name="followers")
    op.drop_index(op.f("ix_followers_follower_id"), table_name="followers")
    op.drop_table("followers")
    # ### end Alembic commands ###
